### ISSUE TITLE
Scrapbook to enex?

### ISSUE THREAD

**Issue by kateto** [danny0838/firefox-scrapbook-converter#2]
Hi Danny -- the description of the add-on says it can convert scrapbook data from and *to* other formats. I'm looking for a way to export a scrapbook to .enex (for Evernote import). Looks like this might not currently be possible with this extension - but maybe I am missing something?

**Comment by danny0838** [comment]
It's meant to be a tool to export data into other formats. However it's quite complicated to convert a web page as well as its linked files to fit in a single enex record. And thus it's still a pending feature.

**Comment by kateto** [comment]
Thanks for the quick reply! I took a look at the two formats (scrapbook's and enex) last night and can see how this would be quite a lot of work. Thanks for taking it on - will keep an eye on the extension for future updates.

**Comment by danny0838** [comment]
We are developing this feature and it is available in the beta channel.

https://addons.mozilla.org/firefox/addon/scrapbookx-converter/versions/beta

Please take a look and see if there is something need to improve.
