### ISSUE TITLE
In "Convert current Scrapbook to .maff", "tree/frame.html" create a wrong link:

### ISSUE THREAD

**Issue by pascallothar** [danny0838/firefox-scrapbook-converter#6]
On _Mac OS X Snow Leopard 10.6.8_, when the _"Entry page"_ text field is filled with **"tree/frame.html"** (default), it is wrongly translate in `tree_frame.html` in the `index.html` file of the created .maff, making the content of this archive not accessible.

**Comment by danny0838** [comment]
Fixed in aeedd064b83ab6c8037291b27864af9fe01fb9d8. Thank you for reporting.
