### ISSUE TITLE
Bookmarks inside the Search_result have wrong URLs

### ISSUE THREAD

**Issue by pascallothar** [danny0838/firefox-scrapbook-converter#8]
Let's open the output of **"Convert current Scrapbook to .maff"** and let's make a search from the _search-box_ of its _side-frame_. If, in the results, we have a **_Bookmark_** (green text), the URL of this bookmark will be wrong. Its correct URL will be appended to the URL of the parent directory of the file `search.html` .

The same behavior happens also for _"Output Tree as HTML..."_.

**Comment by danny0838** [comment]
This is a but for ScrapBook X rather than ScrapBook X Converter. It has been fixed in 1.12.33. Thank you for reporting.
